name: CI - Execute tests


on:
  schedule: #run every day at 3AM
    - cron: '0 3 * * *'
  push:
    branches: [ "develop" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose environment'
        required: false
        type: choice
        options:
          - local-environment
          - test-environment
          - prod-environment
      suites:
        description: 'Choose test suite'
        required: true
        type: choice
        options:
          - regression_suite
          - sanity_suite
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Set variables
        env:
          DEFAULT_ENV_TEST: 'test-environment'
          DEFAULT_TEST_SUITE: 'regression_suite'
        run: |
          echo "ENVIRONMENT=${{ github.event.inputs.environment || env.DEFAULT_ENV_TESTS}}" >> $GITHUB_ENV
          echo "TEST_SUITE=${{ github.event.inputs.type || env.DEFAULT_TEST_SUITE}}" >> $GITHUB_ENV
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'
          cache: 'maven'

      - name: Install Google Chrome # Using shell script to install Google Chrome
        run: |
              chmod +x ./scripts/InstallChrome.sh
                          ./scripts/InstallChrome.sh

      - name: Run tests from maven
        run: mvn clean test -U -P=${{ env.ENVIRONMENT }} '-Dtest.suite=${{ env.TEST_SUITE }}'

#      - name: Deploy report to GH Pages
#        run: JamesIves/github-pages-deploy-actions@4.1.5
#        with:
#          branch: gh-pages
#          folder: ./test-output/report/ #add the correct path to the report



